{% set python_min = '3.10' %}
{% set name = "txl-local-contents" %}
{% set version = "0.2.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/txl_local_contents-{{ version }}.tar.gz
  sha256: fa5950cbf6a9aba365d6a2360c1230f4339e9545322dfae36129b9cc1ba14352

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - txl >=0.2.18,<0.3.0
    - anyio >=3.7.0,<5
    - jupyter_ydoc >=3.0.2,<4.0.0

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  requires:
    - python {{ python_min }}
  imports:
    - txl_local_contents

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/local_contents
  summary: TXL plugin for local contents
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/local_contents
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
