{% set name = "txl-local-contents" %}
{% set version = "0.2.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/txl_local_contents-{{ version }}.tar.gz
  sha256: cf7414b666a87da02fc17ec71300e69dce4576d76d05381c1611dc78349c06f3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.10
    - pip
    - hatchling
  run:
    - python >=3.10
    - txl
    - anyio >=3.7.0,<5
    - jupyter_ydoc >=2.0.0,<3.0.0

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  imports:
    - txl_local_contents

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/local_contents
  summary: TXL plugin for local contents
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/local_contents
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
